### PR TITLE
Fix rest-layer-mem behaviour regarding array fields to match MongoDB.…

### LINKED ISSUE #187: Behaviour of query/predicate does not match behaviour of MongoDB storage backend
The behaviour of the filter operators in the `query` package does not work when the document field being matched against is an array. For example, given the following document and query, the MongoDB storage backend will return a match, while the `resource/testing/mem` backend will not.

### Document
`
  {
    "foo": ["bar", "baz"]
  }
`

### Query
`
{ field: { $in: ["bar"] } }
`

This is the case for the following operators, `$eq`, `$in` `$ne`, `$nin`.

### PR DESCRIPTION
**Pull request by Dragomir-Ivanov**
… Fixes #187

### CODE REVIEW

File: schema/query/predicate.go [hunk 1]
```diff
@@ -232,7 +232,23 @@ type Equal struct {
 
 // Match implements Expression interface.
 func (e Equal) Match(payload map[string]interface{}) bool {
-	return reflect.DeepEqual(getField(payload, e.Field), e.Value)
+	value := getField(payload, e.Field)
+
+	// The $eq(not present in rest-layer) operator in MongoDB allows matching both single values and an
```
Comment (smyrman) [inline schema/query/predicate.go]: I guess you can state "the equality operator" instead of "$eq". What was meant was the implicit equality check as represented by `query.Equal`. Writing `$eq` in the issue was inaccurate.

File: schema/query/predicate.go [hunk 2]
```diff
@@ -255,7 +271,23 @@ type NotEqual struct {
 
 // Match implements Expression interface.
 func (e NotEqual) Match(payload map[string]interface{}) bool {
-	return !reflect.DeepEqual(getField(payload, e.Field), e.Value)
+	value := getField(payload, e.Field)
+
+	// The $ne operator in MongoDB allows matching both single values and an
+	// array of values.
```
Comment (smyrman) [inline schema/query/predicate.go]: FYI: Just did a small test in the MongoDB shell to confirm this is how `$ne` works.

```
> db.c.insert({"a":["a","b"]})
WriteResult({ "nInserted" : 1 })
> db.c.insert({"a":["c","b"]})
WriteResult({ "nInserted" : 1 })
> db.c.insert({"b":"z"})
WriteResult({ "nInserted" : 1 })
> db.c.find({"a":"a"})
{ "_id" : ObjectId("5bfc84458014a3148be6f734"), "a" : [ "a", "b" ] }
> db.c.find({"a":{"$ne":"a"}})
{ "_id" : ObjectId("5bfc844f8014a3148be6f735"), "a" : [ "c", "b" ] }
{ "_id" : ObjectId("5bfc846e8014a3148be6f736"), "b" : "z" }
```
